try{
let a;
console.log(a.length);
} catch(e){
    console.log("your code is incorrect");
}

console.log("this line is also run");